#!/usr/bin/env bash

cd ~/android/kernel/982t
export CROSS_COMPILE=/home/kirito9/android/toolchain/arm-eabi-5.3/bin/arm-eabi-
cd ~/android/kernel/982t/kernel
make mrproper
cd ../
export ARCH=arm
#./makeMtk mts982t n k
./makeMtk -t -o=TARGET_BUILD_VARIANT=user mts982t n k

#Customizing kernel
#cd ~/android/kernel/982t/kernel
#export TARGET_PRODUCT=mts982t
#make mediatek-configs
#make menuconfig
